package main.java.lab1;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package lab1;

public class Library {
	public static void main(String arg[]) {
		System.out.println("HAHA");
	}
}
